[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "emilia"
version = "1.0.0"
dependencies = [
    "ollama",
    "ddgs",
    "kopilogs",
    "trafilatura",
]

[project.scripts]
emilia = "emilia.main:main"

[tool.kuvy.run-paths]
main = "src/emilia/main.py"
tests = "tests/tests.py"
